name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger workflow on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual workflow triggering from the GitHub UI

jobs:
  build-and-release:
    name: Build and Release Executables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23" # Specify the Go version

      - name: Build Binaries
        run: |
          mkdir -p dist
          # Build for Windows (AMD64)
          GOOS=windows GOARCH=amd64 go build -o dist/webdav-server-windows.exe .
          # Build for macOS (AMD64)
          GOOS=darwin GOARCH=amd64 go build -o dist/webdav-server-macos-amd64 .
          # Build for macOS (ARM64)
          GOOS=darwin GOARCH=arm64 go build -o dist/webdav-server-macos-arm64 .
          # Build for Linux (AMD64)
          GOOS=linux GOARCH=amd64 go build -o dist/webdav-server-linux .
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: binaries
          path: dist/*
